[workspace]
authors = ["Alexander Fischer <alexander-fischer1801@t-online.de>"]
channels = ["conda-forge"]
name = "blog"
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]
render = "quarto render"
preview = "quarto preview"
clean = "quarto render --clean"

[dependencies]
quarto = ">=1.9.38,<2"
r-base = ">=4.5.3,<4.6"
r-knitr = ">=1.51,<2"
r-rmarkdown = ">=2.31,<3"
