---
date: "2019-05-28"
title: About
type: section
---

Hi all, I'm Alex!

I am a data scientist at [trivago](http://trivago.com/), where I work on online auctions.
In my free time, I work on open source software for econometrics and statistical inference in **Python** and **R**.


-   [`pyfixest`](https://github.com/py-econometrics/pyfixest) is a **Python** package for fast high-dimensional fixed effects regression, mirroring the syntax and functionality of the R `fixest` package. It supports OLS, WLS, IV, Poisson, and GLM regressions, along with difference-in-differences estimators, quantile regression, and various robust variance-covariance estimators.
-   [`maketables`](https://github.com/py-econometrics/maketables) is a **Python** package for generating publication-ready tables from statistical models and descriptive statistics, with export support for HTML, LaTeX, and Word.
-   [`fwildclusterboot`](https://github.com/s3alfisc/fwildclusterboot) and [`wildboottest`](https://github.com/s3alfisc/wildboottest) implement the fast **wild cluster bootstrap** algorithm as suggested in [Roodman, MacKinnon, Nielsen & Webb](https://journals.sagepub.com/doi/abs/10.1177/1536867X19830877) and [MacKinnon, Nielsen & Webb (2022)](https://www.econ.queensu.ca/sites/econ.queensu.ca/files/wpaper/qed_wp_1485.pdf) in **R** and **Python**.


You can find me on [GitHub](https://github.com/s3alfisc) and [r-universe](https://s3alfisc.r-universe.dev/ui#builds).
